//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HABsMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class habs_alert
    {
        public int user_id { get; set; }
        public string user_email { get; set; }
        public short email_status { get; set; }
        public string location_id { get; set; }
    
        public virtual habs_area habs_area { get; set; }
    }
}
